name: 'Create and merge build change'

description: 'This action will create a pull request, approve the change, and merge it back in using the provided tokens.'

inputs:
  base-branch:
    description: 'The branch you want to merge changes into.'
    required: true
  head-branch:
    description: 'The branch that contains the changes you want to merge.'
    required: true
  repository-name:
    description: 'The name of the repository where the PR will be created.  Defaults to the repository where the action is used.'
    required: false
  owner-name:
    description: 'The name of the owner (user or organization) for the repo where the PR will be created.  Defaults to the owner where the action is used.'
    required: false
  pr-title:
    description: 'The title of the PR.'
    required: true
  github-token:
    description: 'The GitHub Action bot token used to create the PR.'
    required: true
  pat-token:
    description: 'The token used to submit a review and merge the PR.'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
